notes/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name="todo"),
    path('del/<str:item_id>', views.remove, name="del"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls'))
]

notes/models.py
from django.db import models
from django.utils import timezone


class Todo(models.Model):
    title = models.CharField(max_length=100)
    details = models.TextField()
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

notes/forms.py
from django import forms
from .models import Todo


class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = "__all__"

notes/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Todo
from .forms import TodoForm


def index(request):
    item_list = Todo.objects.order_by("-date")
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            form.save()
    form = TodoForm()

    context = {
        "forms": form,
        "list": item_list,
        "title": 'ToDo List',
    }

    return render(request, 'notes/index.html', context)


def remove(request, item_id):  # function to remove item
    item = Todo.objects.get(id=item_id)
    item.delete()
    messages.info(request, "Item was deleted!")
    return redirect('todo')

notes/templates/notes/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>

<meta charset="utf-8">
<title>{{title}}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<style>
    .card {

    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.5),
                0 6px 20px 0 rgba(0,0,0,0.39);
    background: lightblue;
    margin-bottom : 5%;
    border-radius: 25px;
    padding : 2%;
    overflow: auto;
    resize: both;
    text-overflow: ellipsis;
    }
    .card:hover{
        background: darkgrey;
    }

    .submit_form{

        text-align: center;
        padding: 3%;
        background: darkgrey;
        border-radius: 25px;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.4),
                    0 6px 20px 0 rgba(0,0,0,0.36);
    }
</style>

</head>

<body class="container-fluid">

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-info">
        <strong>{{message}}</strong>
    </div>
    {% endfor %}
    {% endif %}

<center class="row">
	<h1><i>My ToDo List</i></h1>
	<hr />
</center>

<div class="row">

	<div class="col-md-6">

	{% for i in list %}
	<div class="card">
		<center><b>{{i.title}}</b></center>
		<hr/>  <!-- (horizontal rule) - a line-break between paragraph-level elements -->
		{{i.date}}
		<hr/>
		{{i.details}}
		<br />
		<br />
		<form action="/del/{{i.id}}" method="POST" style=" padding-right: 4%; padding-bottom: 3%;">
		{% csrf_token %}
		<button value="remove" type="submit" class="btn btn-primary" style="float: right;"><span class="glyphicon glyphicon-trash"></span> remove</button>
		</form>
	</div>
	{% endfor%}
	</div>
	<div class="col-md-1"> </div>
	<div class="col-md-4" >
            <div class="submit_form">
            <form method="POST">
            {% csrf_token %}
                {{ forms }}
               <!-- <label for="id_title">Title:</label>
                <br />
                <input id="id_title" type="text" name="title" maxlength="100" required="">
<br />
                <label for="id_details">Details:</label>
                <textarea id="id_details" name="details" cols="47" rows="10" required=""></textarea>

                <label for="id_date">Date:</label>
                <br />
                <input id="id_date" type="text" name="date" value={{ date }} > -->
            <center>
            <input type="submit" class="btn btn-default" value="submit" />
        </center>
        </form>
        </div>
    </div>
</div>
</body>

</html>